// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameCatalogue.Infrastructure.Persistence;

#nullable disable

namespace VideoGameCatalogue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    partial class CatalogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameCatalogue.Domain.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("VideoGames", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Open-world exploration across the kingdom of Hyrule.",
                            Genre = "Action-Adventure",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Rating = 9.7m,
                            ReleaseDate = new DateOnly(2017, 3, 3),
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A story-driven open-world RPG set in a dark fantasy universe.",
                            Genre = "RPG",
                            Platform = "PC",
                            Publisher = "CD Projekt",
                            Rating = 9.8m,
                            ReleaseDate = new DateOnly(2015, 5, 19),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A vast open world crafted by FromSoftware and George R. R. Martin.",
                            Genre = "Action RPG",
                            Platform = "PlayStation 5",
                            Publisher = "Bandai Namco",
                            Rating = 9.6m,
                            ReleaseDate = new DateOnly(2022, 2, 25),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Defy the god of the dead in a fast-paced roguelike dungeon crawler.",
                            Genre = "Roguelike",
                            Platform = "PC",
                            Publisher = "Supergiant Games",
                            Rating = 9.3m,
                            ReleaseDate = new DateOnly(2020, 9, 17),
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 5,
                            Description = "An epic tale of life in America's unforgiving heartland.",
                            Genre = "Action-Adventure",
                            Platform = "Xbox One",
                            Publisher = "Rockstar Games",
                            Rating = 9.7m,
                            ReleaseDate = new DateOnly(2018, 10, 26),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Build the farm of your dreams in this charming country-life RPG.",
                            Genre = "Simulation",
                            Platform = "PC",
                            Publisher = "ConcernedApe",
                            Rating = 8.9m,
                            ReleaseDate = new DateOnly(2016, 2, 26),
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Kratos and Atreus journey through the Nine Realms.",
                            Genre = "Action-Adventure",
                            Platform = "PlayStation 5",
                            Publisher = "Sony Interactive Entertainment",
                            Rating = 9.4m,
                            ReleaseDate = new DateOnly(2022, 11, 9),
                            Title = "God of War Ragnarök"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Explore a vast interconnected world of insects and heroes.",
                            Genre = "Metroidvania",
                            Platform = "Nintendo Switch",
                            Publisher = "Team Cherry",
                            Rating = 9.0m,
                            ReleaseDate = new DateOnly(2017, 2, 24),
                            Title = "Hollow Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
